POST http://localhost:7770/api/auth/login
Content-Type: application/json

{
  "email": "disparbud@focuson.test",
  "password": "123"
}

### Get all products
GET http://localhost:7770/api/data/calculateFairScore


### Post addListAkun
POST http://localhost:7770/api/addListAkun
Content-Type: application/json

{
    "client_account": "Ismail",
    "platform": "instagram",
    "kategori": "Ismail",
    "username": "sys_interrupted"
}

### Get ListAkun
GET http://localhost:7770/accounts/ListAkun

### Delete ListAkun
DELETE http://localhost:7770/api/deleteListAkun/129

### Edit ListAkun
PUT http://localhost:7770/api/editListAkun/130
Content-Type: application/json

{
    "client_account": "Anugrah",
    "platform": "instagram",
    "kategori": "Anugrah",
    "username": "ismailisme"
}

### post addDataUser per hari
POST http://localhost:7770/fair/addDataUser


### post processData
POST http://localhost:7770/fair/processData

### GET processData
GET http://localhost:7770/api/data/getData

### GET processData
GET http://localhost:7770/api/getFollowers?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET processData
GET http://localhost:7770/api/getDailyInteractions?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Tiktok

### GET processData
GET http://localhost:7770/api/getActivities?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET processData
GET http://localhost:7770/api/getInteractions?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET processData
GET http://localhost:7770/api/getResponsiveness?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET processData
GET http://localhost:7770/api/getFairScores?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-09&platform=Instagram


### GET processData
GET http://localhost:7770/api/getAllPost?page=1&perPage=5&kategori=disparbud&start_date=2025-01-01&end_date=2025-02-09&platform=instagram

### GET rank
GET http://localhost:7770/api/getFairRanking?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET fair score
GET http://localhost:7770/api/getFairScores?customer_username=kemenkoinfra&start_date=2025-01-01&end_date=2025-01-09


### Proses Performa Konten
POST http://localhost:7770/api/prosesPerformaKonten
Content-Type: application/json

{
  "startDate": "2025-01-01",
  "endDate": "2025-02-13"
}


### Get Instagram User Data
GET http://localhost:7770/instagram/getData?kategori=disparbud

### Get Tiktok User Data
GET http://localhost:7770/tiktok/getData

### Get Instagram User Post
GET http://localhost:7770/instagram/getPost?kategori=disparbud

### Get Instagram User Post
GET http://localhost:7770/tiktok/getPost

### Get Instagram User Post
GET http://localhost:7770/instagram/getComment

### Get Instagram User Post
GET http://localhost:7770/instagram/getChildComment

### Get Instagram User Post
GET http://localhost:7770/tiktok/getComment




### Get Instagram User Data
GET http://localhost:7770/api/getAllUsers?kategori=disparbud&platform=Instagram&username=budpardepok

### Get All Username Data
GET http://localhost:7770/api/getAllUsername?kategori=disparbud&platform=Instagram

### Get Picture Data
GET http://localhost:7770/api/getPictureData?kategori=disparbud&platform=Instagram&username=disparbudbandungbarat