###
GET http://localhost:7770/instagram/update-followers-kdm
Content-Type: application/json

###
GET http://localhost:7770/api/v1/labeling
Content-Type: application/json

###
GET http://localhost:7770/api/v1/post-labeling
Content-Type: application/json

###
GET http://localhost:7770/api/v1/comments-coding
Content-Type: application/json

###
GET http://localhost:7770/api/v1/reply-coding/api/v1/comments-coding
Content-Type: application/json

###
GET http://localhost:7770/api/v1/comments-sentiment
Content-Type: application/json

###
GET http://localhost:7770/api/v1/reply-sentiment
Content-Type: application/json




###
POST http://localhost:7770/api/auth/login
Content-Type: application/json

{
  "email": "disparbud@focuson.test",
  "password": "123"
}

### Get all products
GET http://localhost:7770/api/data/calculateFairScore





### GET processData
GET http://localhost:7770/api/data/getData

### GET processData
GET http://localhost:7770/api/getFollowers?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET processData
GET http://localhost:7770/api/getActivities?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET processData
GET http://localhost:7770/api/getInteractions?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET processData
GET http://localhost:7770/api/getResponsiveness?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET processData
GET http://localhost:7770/api/getFairScores?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-09&platform=Instagram


### GET processData
GET http://localhost:7770/api/getAllPost?page=1&perPage=5&kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET rank
GET http://localhost:7770/api/getFairRanking?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET fair score
GET http://localhost:7770/api/getFairScores?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET fair score
GET http://localhost:7770/api/getFollowersRanking?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### STEP 1 ###

### Post addListAkun
POST http://localhost:7770/api/addListAkun
Content-Type: application/json

{
    "client_account": "Ismail",
    "platform": "instagram",
    "kategori": "Ismail",
    "username": "sys_interrupted"
}

### Get ListAkun
GET http://localhost:7770/accounts/ListAkun

### Delete ListAkun
DELETE http://localhost:7770/api/deleteListAkun/129

### Edit ListAkun
PUT http://localhost:7770/api/editListAkun/130
Content-Type: application/json

{
    "client_account": "Anugrah",
    "platform": "instagram",
    "kategori": "Anugrah",
    "username": "ismailisme"
}

### List Akun Mitra / Kategori nya

- opdbekasikab bekasi khusus (instagram) doang
- disparbud (Instagram dan TikTok) 
- disparbud_competitor (Instagram dan TikTok) 
- disparbud_ambassador (Instagram dan TikTok)
- bkkbn_jabar (Instagram)
- prokopim_bekasikab (Instagram)

### Get Instagram User Data
GET http://localhost:7770/instagram/getData?kategori=disparbud_ambassador

### Get Tiktok User Data
GET http://localhost:7770/tiktok/getData?kategori=disparbud

### Get Instagram User Post
GET http://localhost:7770/instagram/getPost?kategori=kdm

### Get TikTok User Post
GET http://localhost:7770/tiktok/getPost?kategori=disparbud

### Get Instagram User Comment
GET http://localhost:7770/instagram/getComment?kategori=kdm_media

### Get TikTok User Comment
GET http://localhost:7770/tiktok/getComment?kategori=kdm

### STEP 2

### post addDataUser per hari
POST http://localhost:7770/fair/addDataUser

### post processData
POST http://localhost:7770/fair/processData
Content-Type: application/json

{
    "start_date": "2025-01-01",
    "end_date": "2025-01-31"
}

### Proses Performa Konten
POST http://localhost:7770/api/prosesPerformaKonten
Content-Type: application/json

{
  "startDate": "2025-01-01",
  "endDate": "2025-02-28"
}

### Get Instagram User Data
GET http://localhost:7770/api/getAllUsers?kategori=disparbud&platform=Instagram&username=budpardepok

### Get All Username Data
GET http://localhost:7770/api/getAllUsername?kategori=disparbud&platform=Instagram

### Get Picture Data
GET http://localhost:7770/api/getPictureData?kategori=disparbud&platform=Instagram&username=disparbudbandungbarat

### Get Fair Data for Insights
GET http://localhost:7770/api/getFairDataInsights?kategori=disparbud&platform=Instagram&month=2025-01&username=purwakartapariwisata

### Get Ai Summary
GET http://localhost:7770/api/getFairSummary?username=smilingbogorcity&month=2025-01&kategori=disparbud&platform=Instagram


### Daily Data // Growth Metrics
### Instagram
### GET Daily Followers
GET http://localhost:7770/api/getDailyLikes?kategori=disparbud&start_date=2025-02-01&end_date=2025-02-28&platform=Instagram

### GET Daily Likes
GET http://localhost:7770/api/getDailyLikes?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET Daily Views
GET http://localhost:7770/api/getDailyViews?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### GET Daily Comments
GET http://localhost:7770/api/getDailyComments?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=Instagram

### TikTok
### GET Daily Followers
GET http://localhost:7770/api/getDailyFollowers?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET Daily Likes
GET http://localhost:7770/api/getDailyLikes?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET Daily Views
GET http://localhost:7770/api/getDailyViews?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET Daily Comments
GET http://localhost:7770/api/getDailyComments?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET Daily Saves
GET http://localhost:7770/api/getDailySaves?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

# ### GET Daily Downloads
# GET http://localhost:7770/api/getDailyDownloads?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok

### GET Daily Shares
GET http://localhost:7770/api/getDailyShares?kategori=disparbud&start_date=2025-01-01&end_date=2025-01-31&platform=TikTok




###
GET http://localhost:7770/api/getGrowthData?username=smilingbogorcity&start_date=2025-02-01&end_date=2025-02-28&platform=Instagram

###
POST http://localhost:7770/file/exportPosts
Content-Type: application/json

{
  "kategori": "prokopim_bekasikab",
  "platform": "Instagram",
  "start_date": "2025-02-01",
  "end_date": "2025-02-28"
}

###
POST http://localhost:7770/file/exportFair
Content-Type: application/json

{
  "kategori": "prokopim_bekasikab",
  "platform": "Instagram",
  "start_date": "2025-02-01",
  "end_date": "2025-02-28"
}

###
GET http://localhost:7770/api/getAllSearchUsername?&platform=Instagram&kategori=prokopim_bekasikab&search=pemkabbekasi

###
GET http://localhost:7770/api/getTotalPost?&platform=TikTok&kategori=disparbud&search=disparbudmajalengka&start_date=2025-02-01&end_date=2025-02-28

###
GET http://localhost:7770/api/getAllPost?perPage=2&page=1&platform=Instagram&kategori=disparbud&start_date=2025-02-01&end_date=2025-02-28&orderBy=performa_konten&direction=desc&username=

###
GET http://localhost:7770/api/getPost?kategori=disparbud&username=disbudpar.bdg&platform=Instagram&start_date=2025-02-01&end_date=2025-02-28

###
GET http://localhost:7770/tiktok/getDataPostByKeywords?kategori=kdm

###
GET http://localhost:7770/instagram/getDataPostByKeywords?kategori=kdm

###
GET http://localhost:7770/youtube/getDataPostByKeywords?kategori=kdm&start_date=2025-02-01&end_date=2025-03-09

###
GET http://localhost:7770/facebook/getDataPostByKeywords?kategori=kdm&start_date=2025-02-01&end_date=2025-03-09

###
POST http://localhost:7770/youtube/getCommentv2
Content-Type: application/json

{
    "kategori": "kdm",
    "fromStart": "true",
    "unique_id_post": [
        "fCBzUwoMSW8"
    ]
}
###
POST http://localhost:7770/youtube/getCommentv3
Content-Type: application/json

{
    "kategori": "kdm",
    "unique_id_post": [
        "OkwWcOtJGvQ"
    ]
}

###
POST http://localhost:7770/tiktok/getCommentv2
Content-Type: application/json

{
    "kategori": "kdm",
    "fromStart": "true",
    "unique_id_post": [
        "7467421508596485382"
    ]
}

###
POST http://localhost:7770/facebook/getCommentv2
Content-Type: application/json

{
    "kategori": "kdm",
    "fromStart": "true",
    "unique_id_post": [
        "1087274276759343",
        "1405192157513638"
    ]
}

###
POST http://localhost:7770/youtube/getCommentv2
Content-Type: application/json

{
    "kategori": "kdm",
    "fromStart": "true",
    "unique_id_post": [
        "O8k8T8ynKpE",
        "Rzjw9WxbGGA",
        "fCBzUwoMSW8",
        "_MnQdqGIJbw",
        "V04VmKn6-G0"
        
    ]
}

###
POST http://localhost:7770/instagram/getPostDataByCode
Content-Type: application/json

{
    "kategori": "kdm",
    "platform": "Instagram",
    "client_account": "kdm@focuson.id",
    "post_code": [
        "DG7vJ-kAGKw",
        "DG8V5CUS4Pw",
        "DG9qctdM8Jb",
        "DG9-NsxN0Bv",
        "DG-KRL9xIzq"
    ]
}

###
GET http://localhost:7770/tiktok/update-followers-kdm